### ISSUE TITLE
calibration directory vs. observation directory

### ISSUE THREAD

**Issue by bakerb845** [LLNL/coda-calibration-tool#1]
Hey Justin,

We're thinking a little more seriously about wrangling this coda calibration tool for our operations pipeline.  One of the concerning things is that every time we process an event we are under the impression that we should be adding the new event envelopes to the existing batch of envelopes.  Our guess is that this workflow could grow unwieldy after a few months and slow down computations while not really improving our results.  Is it in the project planning to enable a sort of one-off where we can simply estimate a magnitude for the event of interest without running through all the recalibrations and adding new envelopes to this ever expanding directory of envelopes?  

Thanks - Ben (University of Utah)

**Comment by justinbarno** [comment]
Hi Ben:

The ability to measure an event against a specific calibration is actually they very next thing on my to-do list for the tool. I don't have a hard timeline just at the moment but I was hoping to get some time to work on that sometime at the end of this month with the hope of having something useful out for people in the mid to late August time-frame.

Nominally the first version of measurement will be very similar to the workflow for calibration and would look something like:
1) Load calibrated model
2) Load envelopes for X events you want to measure
3) Make measurements
4) Export measurements
5) Clear envelopes and repeat from 1/2 depending on if you are in the same region or not for more new events.

This workflow is workable in the short term and I can re-use much of the machinery and API already created for the calibration tool to speed up the turnaround time. I think this workflow would reasonably support the interactive/batch split too. 

In the very short term, since I'm planning to leverage as much of the existing REST API as I can, you can at least run the calibration service as is and test out the load/request/export-results/delete/load-new-data loop in your system. At that point you should, nominally, only need to tweak the scripts/software in your system to call a measurement request endpoint instead of the calibration one.

I can however see that this is not necessarily the most optimal workflow long term and I can think of many improvements that the community might want. For instance I could easily imagine wanting to have a polygon defining a region on the earth that a model is associated with as a 'valid' calibration coverage area for that model and then a user could load up N of said models and the measurement tool would test for coverage and use only those models that have coverage. There are no short term plans for that given there would be both technical challenges making a new workflow/API set for that (boils down to time, mostly) and some procedural ones (e.g. how do we handle models overlapping?).

I would be interested in hearing from you and others in the community about your thoughts on how you envision using a measurement tool!

**Comment by justinbarno** [comment]
As of 1.0.7 this feature is now functionally complete and is available on the "Measured Mw" tab off the main panel. We also have a Jupyter notebook example using ObsPy and the REST endpoints for CCT to accomplish the same. I think there are still many improvements to be made but those are for future tickets.
